[package]
name = "legato-polymarket"
version = "0.1.0"
authors = []

[addresses]
market_addr = "ab3922ccb1794928abed8f5a5e8d9dac72fed24f88077e46593bed47dcdb7775"
legato_vault_addr = "4ff2dae2ed7e9df56074c2e5f17ce407279dc308400b80dad069fa7eaa0612c5"
aptos_framework = "0x1"
aptos_fungible_asset = "0xA"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.legato-vault]
git = "https://github.com/tamago-labs/legato-finance.git"
rev = "main"
subdir = "packages/aptos_vault"


[dev-dependencies]
